name: Deployment

on:
  push:
    branches:
      - main
      - dev

env:
  MONGODB_DB_NAME: env-demo

jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest

    env:
      MONGODB_CLUSTER_ADDRESS: ${{ secrets.MONGODB_CLUSTER_ADDRESS }}
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080

    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Start server
        run: |
          echo "Starting server on port $PORT"
          npm start & npx wait-on http://127.0.0.1:$PORT

      - name: Run tests
        run: npm test

      - name: Output info
        run: |
          echo "Database: $MONGODB_DB_NAME"
          echo "Cluster: $MONGODB_CLUSTER_ADDRESS"
          echo "User: $MONGODB_USERNAME"
